### PR TITLE
Adding russian localization

### PR DESCRIPTION
**Pull request by bigenergy**

### CODE REVIEW

**Comment by bigenergy** [comment]
@phantamanta44 pls merge

**Comment by phantamanta44** [comment]
ah sorry, i was trying to find someone to review this but i couldn't get any russian speakers. i'll merge if you update to support the latest changes and fix the name for the 1x spec processor. thanks

**Comment by bigenergy** [comment]
Sorry, but it looks like I already deleted that repository. You can merge this? I will update this after merge.

**Comment by phantamanta44** [comment]
it's just one file; should be easy to refork and copy it over. please make another PR, i guess

**Pull request closed without merging**
